{% set name = "google-weather-tools" %}
{% set version = "0.3.2" %}
{% set git_rev = "conda-candidate-v0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/google/weather-tools.git
  git_rev: "v{{ version }}"

build:
  noarch: python
  number: 0
  script: >
    {{ PYTHON }} -m pip install . -vv && 
    {{ PYTHON }} -m pip install ./weather_dl -vv && 
    {{ PYTHON }} -m pip install ./weather_mv -vv && 
    {{ PYTHON }} -m pip install ./weather_sp -vv 

requirements:
  build:
    - gdal =3.5.1
    - pip
    - python =3.8
  host:
    - pip
    - python =3.8
    - setuptools_scm
  run:
    - apache-beam[gcp] ==2.40.0
    - earthengine-api >=0.1.263
    - gdal =3.5.1
    - metview-batch
    - python =3.8
    - pip

test:
  imports:
    - weather_dl
    - weather_mv
    - weather_mv.loader_pipeline
    - weather_sp
    - weather_sp.splitter_pipeline
  requires:
    - absl-py
    - apache-beam
    - cdsapi
    - cfgrib
    - dataclasses
    - earthengine-api
    - ecmwf-api-client
    - flake8
    - gdal
    - geojson
    - google-apitools
    - google-cloud-bigquery
    - google-cloud-datastore
    - google-cloud-firestore
    - google-cloud-storage
    - metview-batch
    - netcdf4
    - numpy
    - pandas
    - pygrib
    - pyproj
    - pytest
    - pytest-subtests
    - pytype
    - rasterio
    - requests
    - rioxarray
    - simplejson
    - urllib3
    - xarray
    - xarray-beam

about:
  home: "https://weather-tools.readthedocs.io/"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Apache Beam pipelines to make weather data accessible and useful."
  doc_url: https://github.com/google/weather-tools/tree/main/docs
  dev_url: https://github.com/google/weather-tools/blob/main/LICENSE

extra:
  recipe-maintainers:
    - blackvvine
    - alxmrs
    - mahrsee1997
