{% set name = "google-weather-tools" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: db9e8566091b72a1f20813f043b356590dc6aefd9f5cc5c983c0cbc9d4faf0e5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python =3.8
    - cdsapi
    - ecmwf-api-client
    - apache-beam[gcp] ==2.40.0
    - numpy
    - pandas
    - xarray
    - requests
    - google-cloud-firestore
    - dataclasses
    - cfgrib
    - netcdf4
    - geojson
    - simplejson
    - rioxarray
    - pyproj
    - gdal
    - pygrib
    - flake8
    - pytest
    - pytest-subtests
    - xarray-beam
    - absl-py
    - metview-batch
    - pip
    - google-cloud-datastore
    - google-cloud-bigquery
    - urllib3 ==1.26.5
    - earthengine-api >=0.1.263
    - google-cloud-storage
  host:
    - pip
    - python =3.8
  run:
    - pip
    - apache-beam[gcp] ==2.40.0
    - python =3.8

test:
  imports:
    - weather_dl
    - weather_dl.download_pipeline
    - weather_mv
    - weather_mv.loader_pipeline
    - weather_sp
    - weather_sp.splitter_pipeline
  requires:
    - absl-py
    - flake8
    - netcdf4
    - numpy
    - pytest
    - pytest-subtests
    - xarray
    - xarray-beam

about:
  home: "https://weather-tools.readthedocs.io/"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Apache Beam pipelines to make weather data accessible and useful."
  doc_url: https://github.com/google/weather-tools/tree/main/docs
  dev_url: https://github.com/google/weather-tools/blob/main/LICENSE

extra:
  recipe-maintainers:
    - blackvvine
    - alxmrs
    - mahrsee1997
