{% set name = "google-weather-tools" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: db9e8566091b72a1f20813f043b356590dc6aefd9f5cc5c983c0cbc9d4faf0e5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python=3.8.13
    - cdsapi=0.5.1
    - ecmwf-api-client=1.6.3
    - apache-beam[gcp]=2.40.0
    - numpy=1.22.4
    - pandas=1.5.1
    - xarray=2022.10.0
    - requests=2.28.1
    - google-cloud-firestore=2.7.0
    - dataclasses=0.8
    - cfgrib=0.9.10.2
    - netcdf4=1.6.1
    - geojson=2.5.0=py_0
    - simplejson=3.17.6
    - rioxarray=0.12.2
    - pyproj=3.4.0
    - gdal=3.5.2
    - pygrib=2.1.4
    - flake8=5.0.4
    - pytest=7.2.0
    - pytest-subtests=0.8.0
    - xarray-beam=0.3.1
    - absl-py=1.3.0
    - metview-batch=5.17.0
    - pip=22.3
    - google-cloud-datastore==2.9.0
    - google-cloud-bigquery==3.3.5
    - urllib3==1.26.5
    - earthengine-api==0.1.329
    - google-cloud-storage==2.2.1
  host:
    - pip
    - python =3.8
    - setuptools_scm
  run:
    - pip
    - apache-beam[gcp] ==2.40.0
    - python =3.8

test:
  imports:
    - weather_dl
    - weather_dl.download_pipeline
    - weather_mv
    - weather_mv.loader_pipeline
    - weather_sp
    - weather_sp.splitter_pipeline
  requires:
    - absl-py
    - flake8
    - netcdf4
    - numpy
    - pytest
    - pytest-subtests
    - xarray
    - xarray-beam

about:
  home: "https://weather-tools.readthedocs.io/"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Apache Beam pipelines to make weather data accessible and useful."
  doc_url: https://github.com/google/weather-tools/tree/main/docs
  dev_url: https://github.com/google/weather-tools/blob/main/LICENSE

extra:
  recipe-maintainers:
    - blackvvine
    - alxmrs
    - mahrsee1997
