{% set name = "firebase-admin" %}
{% set version = "5.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 05e0c12e37a613b6aeeb2a96d4259badf139f977cb2ac630fd364722ee02a74d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cachecontrol >=0.12.6
    - google-api-core[grpc] >=1.22.1,
    - google-api-python-client >=1.7.8
    - google-cloud-firestore >=2.1.0
    - google-cloud-storage >=1.37.1
    - python >=3.6

test:
  imports:
    - firebase_admin

about:
  home: "https://firebase.google.com/docs/admin/setup/"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Firebase Admin Python SDK"
  doc_url: https://firebase.google.com/docs/reference/admin/python/
  dev_url: https://github.com/firebase/firebase-admin-python

extra:
  recipe-maintainers:
    - blackvvine
