{% set name = "google-cloud-storage" %}
{% set version = "2.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0244f4612710cb5ec445fc6774387564e23f9823363fb408b28724e2102401b7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python>=3.8
  run:
    - google-api-core >=1.31.5,
    - google-auth >=1.25.0,
    - google-cloud-core >=1.6.0,
    - google-resumable-media >=2.3.2
    - protobuf
    - python>=3.8
    - requests >=2.18.0

test:
  imports:
    - google
    - google.cloud
    - google.cloud.storage

about:
  home: "https://github.com/googleapis/python-storage"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Google Cloud Storage API client library"
  doc_url: https://cloud.google.com/python/docs/reference/storage/2.2.1
  dev_url: https://github.com/googleapis/python-storage

extra:
  recipe-maintainers:
    - blackvvine
